[default]
template_dir = "api/templates/" 
# secret_key = "Dpg2pArH611t8v" // Error: failed to extract configuration

[global]
address = "0.0.0.0"

[development]
address = "0.0.0.0"

[default.databases.sea_orm]
# Mysql
# make sure to enable "sqlx-mysql" feature in Cargo.toml, i.e default = ["sqlx-mysql"]
url = "mysql://admin1:aftertime01@ktor-kafka-database-1.c00hcyln51ck.ap-northeast-2.rds.amazonaws.com:3306/tokio_tungstenite_rocket"
# url = "mysql://admin01:aftertime01@10.46.40.102:3306/tokio_tungstenite_rocket"

# Postgres
# make sure to enable "sqlx-postgres" feature in Cargo.toml, i.e default = ["sqlx-postgres"]
# url = "postgres://user:pass@localhost:5432/rocket"
