[default]
template_dir = "api/templates/"
address = "0.0.0.0" 

[global]
# address = "0.0.0.0"

[debug]
address = "121.172.169.213"

[release]
address = "121.172.169.213"
secret_key = "floatingtruthagreetightpoorfootballknowledge"

[default.databases.sea_orm]
# Mysql
# make sure to enable "sqlx-mysql" feature in Cargo.toml, i.e default = ["sqlx-mysql"]
url = "mysql://local_admin:password@121.172.169.213:3306/tokio_tungstenite_rocket"
# url = "mysql://admin01:aftertime01@10.46.40.102:3306/tokio_tungstenite_rocket"

# Postgres
# make sure to enable "sqlx-postgres" feature in Cargo.toml, i.e default = ["sqlx-postgres"]
# url = "postgres://user:pass@localhost:5432/rocket"
