//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use rocket::serde::{Deserialize, Serialize};
use rocket_okapi::okapi::schemars::{self, JsonSchema};
use validator::{Validate, ValidationError};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize, JsonSchema, Validate)]
#[serde(crate = "rocket::serde")]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    #[validate(email)]
    pub email: String,
    pub password: String,
    pub firstname: Option<String>,
    pub lastname: Option<String>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    // #[sea_orm(has_many = "super::author::Entity")]
    // Author,
    // #[sea_orm(has_many = "super::book::Entity")]
    // Book,
}

// impl Related<super::author::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Author.def()
//     }
// }

// impl Related<super::book::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Book.def()
//     }
// }

impl ActiveModelBehavior for ActiveModel {}
